### ISSUE TITLE
Software Design Patterns

### ISSUE THREAD

**Issue by Zubaeyr** [zellwk/ama#2]
Although there are lots of tutorials available Online about Design Patterns, none of them have good quality and clear explanation. They just explain the definition but fails to explain the following questions 
1. Why, when and where, will we be needing them? 
2. How are they actually useful and better than the standard practices?
3. Why should we learn them?
4. How to use them?
Need lots of real world example for each of the design pattern. In depth explanation of each pattern would be real helpful.  Most of the other tutorials only has "how to use" part, but leaves out other W's, which I believe is quite essential for understanding and learning. I would prefer explanation with Java.

**Comment by zellwk** [comment]
What design patterns are you referring to

**Comment by Zubaeyr** [comment]
```
Factory Pattern
Abstract Factory Pattern
Singleton Pattern
Builder Pattern
Prototype Pattern
Adapter Pattern
Bridge Pattern
Filter Pattern
Composite Pattern
Decorator Pattern
Facade Pattern
Flyweight Pattern
Proxy Pattern
Chain of Responsibility Pattern
Command Pattern
Interpreter Pattern
Iterator Pattern
Mediator Pattern
Memento Pattern
Observer Pattern
State Pattern
Null Object Pattern
Strategy Pattern
Template Pattern
Visitor Pattern
MVC Pattern
Business Delegate Pattern
Composite Entity Pattern
Data Access Object Pattern
Front Controller Pattern
Intercepting Filter Pattern
Service Locater Pattern
Transfer Object Pattern
```

**Comment by zellwk** [comment]
Why make things complicated? Pick 1 or 2 patterns that you feel are good, then run with it. If it's not good enough, you'll understand as you go along. Don't let decision paralysis stop you.

**Comment by zellwk** [comment]
Closing this thread. Feel free to open if you want to continue the conversation
