### ISSUE TITLE
Using Susy to create a front end framework

### ISSUE THREAD

**Issue by KevinAdu** [zellwk/ama#4]
Hi Zell,

Until now I’ve been using HTML grids on my projects. I’ve used both Bootstrap and Foundation’s grid system and I thought they were a revelation in the beginning but after some time I started to realised the HTML markup starts to become really cluttered and sometimes hard to maintain. So now I have been looking at CSS grids and especially Susy.

I have one question for you. Right now I have project where I have to create a framework which will be a central repository of styles for our new greenfield project and hopefully many other projects in the future. Normally to be able to supply grid layout styles, I would supply layout grid styles so that the user can use position their content freely using the grid layout's class declarations similar to Bootstrap. Using Susy, how would I supply layout grid styles?

**Comment by zellwk** [comment]
Have you read these two articles yet?
- http://zellwk.com/blog/migrating-from-bootstrap-to-susy/
- http://zellwk.com/blog/from-html-grids-to-css-grids/

**Comment by KevinAdu** [comment]
The second article I hadn't seen before and definitely helped me out.
Thanks a lot mate.
