### ISSUE TITLE
File-based CMS recommendation

### ISSUE THREAD

**Issue by danielkorpai** [zellwk/ama#5]
Hey Zell,

First of all, thanks for all the articles you wrote about your work as a designer and front-end developer. 

I'm also a designer and front-end developer, but in the last couple of months my clients want me to create them the CMS for their websites besides the front-end part. I'm totally aware of building and manages databases is not my role as a front-end developer, but recently I started to think about a middle-way solution.

Since, I don't want the hassle that comes with Wordpress, I started to look for alternative solutions. This is how I found [Kirby](https://getkirby.com), which is a file-based CMS system.

I also read your [article](http://zellwk.com/blog/deploy-static-site/) about using Jekyll (I'm aware of Jekyll doesn't have an admin panel), but makes managing content much easier. 

So my question is: do you have any recommendation what can I use for file-based CMS, which also has an admin panel suitable for clients? Or do you recommend me to dive deep into the Wordpress world? What is your reaction when clients ask for an admin panel for their websites?

Thank you very much for your time and answer!

**Comment by zellwk** [comment]
I haven't used Kirby personally, but I'll intend to try it out the next time I work with a client that wants a CMS. It looks good enough to satisfy most criteria. 

I would check with them on what they need, then recommend accordingly. As much as possible, I don't want to hop into the Wordpress world anymore. But if they have a solid reason to use Wordpress, then I'll go with Wordpress. 

Does this help?

**Comment by danielkorpai** [comment]
Thank you for your answer! :) 

I'm happy that we're on the same size in terms of avoiding Wordpress as much as possible. 
Well, 99% of my clients only want to modify texts and replace images. That's all. (If they want to have more complex modifications they always contact me anyway.)

Depending on this information can you be please more specific with your answer? 

(Or your clients never asks for some level of CMS?)

Thank you for your answer :)

**Comment by zellwk** [comment]
Yep sure. I'll either go with Kirby or Contentful. It depends on the priorities of your clients though. I say choose what you think is best, then explain why you think so. 

(I mostly work with agencies, so I don't get much clients at this point).

**Comment by danielkorpai** [comment]
Thank you for your answer! I haven't heard about Contentful before, so I'll give it a try as well. From my part you can close this issue and thank you again for your help! :)

**Comment by zellwk** [comment]
Cool. Let me know what works best, and why :)
