### ISSUE TITLE
How to make a responsive gallery collapse to one column?

### ISSUE THREAD

**Issue by swthate** [zellwk/ama#6]
Hi Zell,

I've been on your newsletter for a long time and have enjoyed a lot of your writing.

**What I want**
My gallery, which is normally `3 of 12` needs to collapse to `12 of 12` or `full` at lower resolutions.

**What I tried**
I tried the pretty straight-forward approach of use something like this:
`@include breakpoint(max-width 660px) { @include gallery(12 of 12); }`
or
`@include breakpoint(max-width 660px) { @include gallery(full); }`

**What happened**
`(12 of 12)` collapses and stacks all gallery elements on top of each other.
`(full)` returns an error in my terminal:

```
Error in plugin 'sass'
Message:
    assets/bower_components/susy/sass/susy/language/susy/_gallery.scss
Error: argument `$number` of `floor($number)` must be a number

       Backtrace:
        assets/bower_components/susy/sass/susy/language/susy/_gallery.scss:24, in function `floor`
        assets/bower_components/susy/sass/susy/language/susy/_gallery.scss:24, in mixin `gallery`
        assets/scss/templates/_counties.scss:22, in mixin `@content`
        assets/bower_components/breakpoint-sass/stylesheets/_breakpoint.scss:66, in mixin `breakpoint`
        assets/scss/templates/_counties.scss:22
        on line 24 of assets/bower_components/susy/sass/susy/language/susy/_gallery.scss
>>   $line         : floor($context / $n);
   ------------------^
```

**Question**
Can galleries collapse to a single column? If so, what is the correct way to do it?

Thanks!

**Comment by zellwk** [comment]
Write mobile-first CSS. This should help: https://zellwk.com/blog/how-to-write-mobile-first-css/
