### ISSUE TITLE
Simple CRUD App Tutorial

### ISSUE THREAD

**Issue by db001** [zellwk/ama#7]
Hi Zell,
Thanks for the tutorial, very easy to follow.

The issue I've got is right at the end with the delete operation.  Using the code in the tutorial, when I click the "Delete first Darth Vader quote" I get an error in the console of:

> Uncaught (in promise) SyntaxError: Unexpected token A in JSON at position 0

The last quote gets removed but only after I've manually refreshed the tab.

If I alter the code in my `del.addEventListener` to match that in your repo and to 

`.then((res) => {
        console.log(res);
        window.location.reload(true);
    })
`

and remove the second `.then(data) => ....` it all works perfectly.  Am I doing something wrong or is there an error in the code?

Thanks.

**Comment by zellwk** [comment]
This should help you debug your `Uncaught (in promise) SyntaxError`, plus the second one. 

https://css-tricks.com/using-fetch/
